# Generated by Django 5.2.5 on 2025-08-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
