# Generated by Django 5.2.5 on 2025-08-28 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproa', '0002_allowedvoter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votante',
            options={'ordering': ['-fecha_voto'], 'verbose_name': 'Votante', 'verbose_name_plural': 'Votantes'},
        ),
        migrations.RemoveField(
            model_name='votante',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='votante',
            name='creado',
        ),
        migrations.AddField(
            model_name='votante',
            name='fecha_voto',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 28, 1, 47, 57, 406535, tzinfo=datetime.timezone.utc), verbose_name='Fecha del voto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votante',
            name='voto',
            field=models.CharField(choices=[('grupo_azul', 'Grupo Azul'), ('grupo_rojo', 'Grupo Rojo'), ('grupo_verde', 'Grupo Verde')], default='grupo_azul', max_length=50, verbose_name='Voto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AllowedVoter',
        ),
    ]
