# Generated by Django 5.2.5 on 2025-08-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproa', '0002_empleado_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
