# Generated by Django 5.2.5 on 2025-08-17 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproa', '0003_votante_delete_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votante',
            options={'ordering': ['nombre'], 'verbose_name': 'Votante', 'verbose_name_plural': 'Votantes'},
        ),
        migrations.AddField(
            model_name='votante',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='votante',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votante',
            name='dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterModelTable(
            name='votante',
            table='votantes',
        ),
    ]
