# Generated by Django 5.2.5 on 2025-08-17 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproa', '0004_alter_votante_options_votante_actualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='apellido',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Apellido completo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votante',
            name='dni',
            field=models.CharField(max_length=8, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
