# Generated by Django 5.2.5 on 2025-08-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproa', '0005_votante_apellido_alter_votante_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='voto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Voto'),
        ),
    ]
