# Generated by Django 5.2.5 on 2025-08-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproa', '0006_votante_voto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votante',
            name='voto',
        ),
    ]
