# Generated by Django 5.2.5 on 2025-08-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproa', '0007_remove_votante_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='votante',
            name='voto',
            field=models.CharField(blank=True, choices=[('grupo_azul', 'Grupo Azul'), ('grupo_rojo', 'Grupo Rojo'), ('grupo_verde', 'Grupo Verde')], max_length=50, null=True, verbose_name='Voto'),
        ),
    ]
